#!/bin/bash

REGION=ap-northeast-1
ACCOUNT_ID=967866550848
ACCESS_KEY=AKIAVRUVTVBZ5ZX2AMFX
SECRET_KEY=igmM8hV2S5kYJYlGXe6lIv5f/DkMdroiQJf3PpdH
COMMIT_HASH=default
ECS_SERVICE_ARN=arn:aws:ecs:ap-northeast-1:967866550848:cluster/example

# Your ECS deployment commands here

# Example ECS Update Service Command
aws ecs update-service \
  --region $REGION \
  --cluster example \
  --service $ECS_SERVICE_ARN \
  --task-definition examplegw:1

# Tag ECS tasks with the commit hash
aws ecs tag-resource \
  --region $REGION \
  --resource-arn $ECS_SERVICE_ARN \
  --tags Key=CommitHash,Value=$COMMIT_HASH
