name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy_infra:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1

    - name: Docker login to AWS ECR
      run: |
        aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 643575754776.dkr.ecr.ap-northeast-1.amazonaws.com


    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve

  deploy_ecr_and_ecs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1


    - name: Authenticate Docker with ECR 
      run: |
        aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 643575754776.dkr.ecr.ap-northeast-1.amazonaws.com


          # - name: Login to AWS ECR
      #      run: |



    - name: Build and Push Docker Image
      run: |
        docker build -t example .
        docker images
        docker tag example:latest 643575754776.dkr.ecr.ap-northeast-1.amazonaws.com/example:latest
        docker push 643575754776.dkr.ecr.ap-northeast-1.amazonaws.com/example:latest

  deploy_to_ecs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2


    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1


    - name: Login to AWS ECR
      run: aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 643575754776.dkr.ecr.ap-northeast-1.amazonaws.com

    - name: Deploy to ECS
      run: /usr/local/bin/ecs-cli compose --file docker-compose.yml up --cluster example

  appmesh_canary_deployment:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Run AppMesh Canary Deployment Script
      run: |
        ./appmesh_canary_deployment_script.sh

